import React, { useState } from 'react';
import { FileCode, Search, Clock, Layers } from 'lucide-react';

export const AeScriptGenerator: React.FC<{ onCancel: () => void }> = ({ onCancel }) => {
  const [layersInput, setLayersInput] = useState('');
  const [targetDuration, setTargetDuration] = useState('5.0');
  const [useOriginalDuration, setUseOriginalDuration] = useState(false);
  const [generatedScript, setGeneratedScript] = useState('');

  const generateScript = () => {
    const layerNames = layersInput.split('\n').filter(line => line.trim() !== '');
    
    let script = `// =========================================================
// After Effects Professional Layer Sync Script
// Generated by SVGA Genius Processor
// =========================================================

(function() {
  var comp = app.project.activeItem;
  
  if (!(comp instanceof CompItem)) {
    alert("يرجى اختيار Composition أولاً.");
    return;
  }

  app.beginUndoGroup("Sync Layer Durations");

  var useOriginal = ${useOriginalDuration};
  var targetDuration = parseFloat('${targetDuration}');
  var layerNames = ${JSON.stringify(layerNames)};
  var notFound = [];

  for (var j = 0; j < layerNames.length; j++) {
    var name = layerNames[j].trim().replace('(hidden)', '');
    var isHidden = layerNames[j].indexOf('(hidden)') !== -1;
    var found = false;

    for (var i = 1; i <= comp.layers.length; i++) {
      var layer = comp.layers[i];
      if (layer.name === name && (!isHidden || !layer.enabled)) {
        var newLayer = layer.duplicate();
        if (!useOriginal) {
          newLayer.outPoint = newLayer.inPoint + targetDuration;
        }
        found = true;
      }
    }
    if (!found) notFound.push(name);
  }

  app.endUndoGroup();

  if (notFound.length > 0) {
    alert("تمت العملية، ولكن لم يتم العثور على الطبقات التالية:\\n" + notFound.join('\\n'));
  } else {
    alert("تمت مزامنة الطبقات بنجاح!");
  }
})();
`;
    setGeneratedScript(script);
  };

  return (
    <div className="bg-slate-900 p-8 rounded-2xl border border-slate-700 shadow-2xl max-w-2xl mx-auto">
      <h2 className="text-3xl font-black text-white mb-6 flex items-center gap-3">
        <FileCode className="text-indigo-500" />
        Professional AE Script Generator
      </h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <div>
          <label className="text-slate-400 font-bold mb-2 block">أسماء الطبقات (واحدة في كل سطر)</label>
          <textarea
            className="w-full h-48 bg-slate-800 text-white p-4 rounded-xl border border-slate-700 focus:border-indigo-500 transition-all"
            placeholder="Layer 1&#10;Layer 2 (hidden)"
            value={layersInput}
            onChange={(e) => setLayersInput(e.target.value)}
          />
        </div>
        
        <div className="space-y-6">
          <div>
            <label className="text-slate-400 font-bold mb-2 block flex items-center gap-2">
              <Clock className="w-4 h-4" /> مدة الطبقات (بالثواني)
            </label>
            <input
              type="number"
              step="0.1"
              className="w-full bg-slate-800 text-white p-3 rounded-xl border border-slate-700 disabled:opacity-50"
              value={targetDuration}
              onChange={(e) => setTargetDuration(e.target.value)}
              disabled={useOriginalDuration}
            />
          </div>
          
          <div className="flex items-center gap-3 bg-slate-800 p-4 rounded-xl">
            <input
              type="checkbox"
              id="useOriginal"
              className="w-5 h-5 accent-indigo-500"
              checked={useOriginalDuration}
              onChange={(e) => setUseOriginalDuration(e.target.checked)}
            />
            <label htmlFor="useOriginal" className="text-white font-bold cursor-pointer">
              استخدام المدة الأصلية للطبقة
            </label>
          </div>
        </div>
      </div>
      
      <button 
        onClick={generateScript} 
        className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-black py-4 rounded-xl text-lg transition-all active:scale-95 shadow-lg shadow-indigo-600/20"
      >
        توليد السكريبت الاحترافي
      </button>
      
      {generatedScript && (
        <div className="mt-8">
          <h3 className="text-lg font-bold text-white mb-3">الكود الناتج (انسخه إلى AE):</h3>
          <pre className="bg-black text-green-400 p-6 rounded-xl overflow-x-auto text-sm font-mono border border-slate-700">
            {generatedScript}
          </pre>
        </div>
      )}
      
      <button onClick={onCancel} className="w-full bg-slate-700 hover:bg-slate-600 text-white font-bold py-3 rounded-xl mt-6">
        إلغاء
      </button>
    </div>
  );
};
